spring.application.name=OnlineCourse

spring.datasource.url=jdbc:postgresql://localhost:8081/online_course_db
spring.datasource.username=online_course_user
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
