###create instructor
POST localhost:8080/instructor/create
Content-Type: application/json

{
  "fullName": "Akbar Sobirov",
  "experience": 8
}

###create instructor

POST localhost:8080/instructor/create
Content-Type: application/json

{
  "fullName": "Hamid Tursunov",
  "experience": 5
}

###create instructor

POST localhost:8080/instructor/create
Content-Type: application/json

{
  "fullName": "Lochinbek Qodirov",
  "experience": 12
}

###create instructor

POST localhost:8080/instructor/create
Content-Type: application/json

{
  "fullName": "Sanjar Normatov",
  "experience": 3
}

###create instructor

POST localhost:8080/instructor/create
Content-Type: application/json

{
  "fullName": "Umid Xasanov",
  "experience": 7
}

###create instructor

POST localhost:8080/instructor/create
Content-Type: application/json

{
  "fullName": "Firdavs Abdullayev",
  "experience": 10
}

###create instructor

POST localhost:8080/instructor/create
Content-Type: application/json

{
  "fullName": "Rustam Qosimov",
  "experience": 6
}

###create instructor

POST localhost:8080/instructor/create
Content-Type: application/json

{
  "fullName": "Eldor Yuldashev",
  "experience": 9
}

###create instructor

POST localhost:8080/instructor/create
Content-Type: application/json

{
  "fullName": "Mansur Raximov",
  "experience": 4
}

###create instructor

POST localhost:8080/instructor/create
Content-Type: application/json

{
  "fullName": "Jahongir Ismoilov",
  "experience": 15
}