###student courses
GET localhost:8080/student/student-courses/1

###student course detailed
GET localhost:8080/student/course-detailed/1

###get no-course students
GET localhost:8080/student/no-course